export default IMAGES = {
  ATHENA: {
    SPLASH100: require('@/assets/images/athena/splash/splash001.jpg'),
    SPLASH101: require('@/assets/images/athena/splash/splash202.png'),
    SPLASH102: require('@/assets/images/athena/splash/splash220.png'),
    SPLASH103: require('@/assets/images/athena/splash/splash203.png'),
    SPLASH104: require('@/assets/images/athena/splash/splash209.png'),
    SPLASH105: require('@/assets/images/athena/splash/splash207.png'),
    SPLASH106: require('@/assets/images/athena/splash/splash210.png'),
    SPLASH107: require('@/assets/images/athena/splash/splash206.png'),
    SPLASH108: require('@/assets/images/athena/splash/splash216.png'),
    SPLASH109: require('@/assets/images/athena/splash/splash208.png'),
    SPLASH110: require('@/assets/images/athena/splash/splash219.png'),
    SPLASH111: require('@/assets/images/athena/splash/splash225.png'),
    FLAG001: require('@/assets/images/athena/flags/flag103.png'),
    FLAG002: require('@/assets/images/athena/flags/flag101.jpeg'),
    FLAG003: require('@/assets/images/athena/flags/flag102.png'),
    FLAG004: require('@/assets/images/athena/flags/flag105.png'),
    FLAG005: require('@/assets/images/athena/flags/flag109.png'),
    FLAG006: require('@/assets/images/athena/flags/flag104.png'),
    FLAG007: require('@/assets/images/athena/flags/flag106.png'),
    FLAG008: require('@/assets/images/athena/flags/flag107.png'),
    FLAG009: require('@/assets/images/athena/flags/flag108.png'),
    DEFAULT: 'https://previews.123rf.com/images/apoev/apoev1804/apoev180400017/98627827-default-placeholder-businesswoman-half-length-portrait-photo-avatar-woman-gray-color.jpg',
  },
  WORLD: {
    LOGO: require('@/assets/images/world/logo.png'),
    W001: require('@/assets/images/world/world001.jpg'),
    W101: require('@/assets/images/world/world101.jpg'),
    W102: require('@/assets/images/world/world102.webp'),
    W103: require('@/assets/images/world/world103.jpg'),
  },
  FITNESS: {
    V1: {
      A101: require('@/assets/images/fitness/v1/avatar101.png'),
      A102: require('@/assets/images/fitness/v1/avatar102.png'),
      A103: require('@/assets/images/fitness/v1/avatar103.png'),
      A104: require('@/assets/images/fitness/v1/avatar104.png'),
      A105: require('@/assets/images/fitness/v1/avatar105.png'),
      A106: require('@/assets/images/fitness/v1/avatar106.png'),
      A107: require('@/assets/images/fitness/v1/avatar107.png'),
      A108: require('@/assets/images/fitness/v1/avatar108.png'),
      A109: require('@/assets/images/fitness/v1/avatar109.png'),
      A110: require('@/assets/images/fitness/v1/avatar110.png'),
      A111: require('@/assets/images/fitness/v1/avatar111.png'),
      A112: require('@/assets/images/fitness/v1/avatar112.png'),
      A113: require('@/assets/images/fitness/v1/avatar113.png'),
      A114: require('@/assets/images/fitness/v1/avatar114.png'),
      A115: require('@/assets/images/fitness/v1/avatar115.png'),
      A116: require('@/assets/images/fitness/v1/avatar116.png'),

      F100: require('@/assets/images/fitness/v1/fitness101.webp'),

      F101: require('@/assets/images/fitness/v1/fitness107.jpg'),
      F102: require('@/assets/images/fitness/v1/fitness115.jpg'),
      F103: require('@/assets/images/fitness/v1/fitness126.jpg'),
      F104: require('@/assets/images/fitness/v1/fitness130.jpg'),
      F105: require('@/assets/images/fitness/v1/fitness152.jpg'),
      F106: require('@/assets/images/fitness/v1/fitness157.webp'),
      F107: require('@/assets/images/fitness/v1/fitness158.webp'),
      F108: require('@/assets/images/fitness/v1/fitness159.webp'),
      F109: require('@/assets/images/fitness/v1/fitness160.webp'),
      F110: require('@/assets/images/fitness/v1/fitness102.webp'),
      F121: require('@/assets/images/fitness/v1/fitness162.jpg'),
      F122: require('@/assets/images/fitness/v1/fitness163.webp'),
      F123: require('@/assets/images/fitness/v1/fitness161.jpg'),
      F124: require('@/assets/images/fitness/v1/fitness156.jpg'),
      F125: require('@/assets/images/fitness/v1/fitness154.webp'),
      F126: require('@/assets/images/fitness/v1/fitness150.jpg'),
      F127: require('@/assets/images/fitness/v1/fitness148.jpg'),
      F128: require('@/assets/images/fitness/v1/fitness147.jpg'),
      F129: require('@/assets/images/fitness/v1/fitness117.jpg'),
      F130: require('@/assets/images/fitness/v1/fitness139.jpg'),
      F131: require('@/assets/images/fitness/v1/fitness134.webp'),
      F132: require('@/assets/images/fitness/v1/fitness132.webp'),
      F133: require('@/assets/images/fitness/v1/fitness131.jpg'),
      F134: require('@/assets/images/fitness/v1/fitness129.webp'),
      F135: require('@/assets/images/fitness/v1/fitness127.jpg'),
      F136: require('@/assets/images/fitness/v1/fitness124.jpg'),
      F137: require('@/assets/images/fitness/v1/fitness121.jpg'),
      F138: require('@/assets/images/fitness/v1/fitness120.jpg'),
      F140: require('@/assets/images/fitness/v1/fitness103.jpg'),
      F141: require('@/assets/images/fitness/v1/fitness104.jpg'),
      F142: require('@/assets/images/fitness/v1/fitness133.jpg'),
      F143: require('@/assets/images/fitness/v1/fitness106.webp'),
      F144: require('@/assets/images/fitness/v1/fitness108.webp'),
      F145: require('@/assets/images/fitness/v1/fitness109.webp'),
      F146: require('@/assets/images/fitness/v1/fitness111.jpg'),
      F147: require('@/assets/images/fitness/v1/fitness112.jpg'),
      F148: require('@/assets/images/fitness/v1/fitness113.jpg'),
      F149: require('@/assets/images/fitness/v1/fitness114.jpg'),
      F150: require('@/assets/images/fitness/v1/fitness116.jpg'),
      F151: require('@/assets/images/fitness/v1/fitness118.jpg'),
      F152: require('@/assets/images/fitness/v1/fitness119.jpg'),
      F153: require('@/assets/images/fitness/v1/fitness122.jpg'),
      F154: require('@/assets/images/fitness/v1/fitness123.jpg'),
      F155: require('@/assets/images/fitness/v1/fitness125.jpg'),
      F156: require('@/assets/images/fitness/v1/fitness128.webp'),
      F157: require('@/assets/images/fitness/v1/fitness137.jpg'),
      F158: require('@/assets/images/fitness/v1/fitness140.webp'),
      F159: require('@/assets/images/fitness/v1/fitness141.jpeg'),
    },
  },
  CHATGPT: {
    V1: {
      LOGO: require('@/assets/images/chatgpt/v1/logo.png'),
      AVATAR: require('@/assets/images/chatgpt/v1/avatar.jpg'),
    },
  },
  PAPER: {
    OLDPAPER: require('@/assets/images/paper/old-paper.jpg'),
  },
  DISNEY: {
    V1: {
      // logos
      logoDisney: require('@/assets/images/disney/v1/logo/disney.png'),
      logoMarvel: require('@/assets/images/disney/v1/logo/marvel.png'),
      logoNatGeo: require('@/assets/images/disney/v1/logo/national-geographic.png'),
      logoPixar: require('@/assets/images/disney/v1/logo/pixar.png'),
      logoStarWars: require('@/assets/images/disney/v1/logo/star-wars.png'),

      // slides
      slideAvatar: require('@/assets/images/disney/v1/slides/avatar.png'),
      slideAvengersEndgame: require('@/assets/images/disney/v1/slides/avengers-endgame.png'),
      slideCaptainMarvel: require('@/assets/images/disney/v1/slides/captain-marvel.png'),
      slideStarWarsMandalorian: require('@/assets/images/disney/v1/slides/star-wars-mandalorian.png'),

      // movies
      a: require('@/assets/images/disney/v1/movies/a.jpg'),
      ae: require('@/assets/images/disney/v1/movies/ae.jpg'),
      aiw: require('@/assets/images/disney/v1/movies/aiw.jpg'),
      anhe4: require('@/assets/images/disney/v1/movies/anhe4.jpg'),
      aotce2: require('@/assets/images/disney/v1/movies/aotce2.jpg'),
      b: require('@/assets/images/disney/v1/movies/b.jpg'),
      batb: require('@/assets/images/disney/v1/movies/batb.jpg'),
      cacw: require('@/assets/images/disney/v1/movies/cacw.jpg'),
      cm: require('@/assets/images/disney/v1/movies/cm.jpg'),
      f: require('@/assets/images/disney/v1/movies/f.jpg'),
      fz: require('@/assets/images/disney/v1/movies/fz.jpg'),
      h: require('@/assets/images/disney/v1/movies/h.jpg'),
      i: require('@/assets/images/disney/v1/movies/i.jpg'),
      p: require('@/assets/images/disney/v1/movies/p.jpg'),
      roasws: require('@/assets/images/disney/v1/movies/roasws.jpg'),
      sb: require('@/assets/images/disney/v1/movies/sb.jpg'),
      swatsd: require('@/assets/images/disney/v1/movies/swatsd.jpg'),
      tesbe5: require('@/assets/images/disney/v1/movies/tesbe5.jpg'),
      tfae7: require('@/assets/images/disney/v1/movies/tfae7.jpg'),
      thond: require('@/assets/images/disney/v1/movies/thond.jpg'),
      tlk: require('@/assets/images/disney/v1/movies/tlk.jpg'),
      tlm: require('@/assets/images/disney/v1/movies/tlm.jpg'),
      tm: require('@/assets/images/disney/v1/movies/tm.jpg'),
      tpme1: require('@/assets/images/disney/v1/movies/tpme1.jpg'),
      ts: require('@/assets/images/disney/v1/movies/ts.jpg'),
      tsits: require('@/assets/images/disney/v1/movies/tsits.jpg'),
      z: require('@/assets/images/disney/v1/movies/z.jpg'),

      // profiles
      elsa: require('@/assets/images/disney/v1/profiles/elsa.jpg'),
      ironMan: require('@/assets/images/disney/v1/profiles/iron-man.jpg'),
      stormtrooper: require('@/assets/images/disney/v1/profiles/stormtrooper.jpg'),
      yoda: require('@/assets/images/disney/v1/profiles/yoda.jpg'),
    }
  }
};