export default IMAGES = {
  ATHENA: {
    SPLASH100: require('@/assets/images/athena/splash/splash001.jpg'),
    SPLASH101: require('@/assets/images/athena/splash/splash202.png'),
    SPLASH102: require('@/assets/images/athena/splash/splash220.png'),
    SPLASH103: require('@/assets/images/athena/splash/splash203.png'),
    SPLASH104: require('@/assets/images/athena/splash/splash209.png'),
    SPLASH105: require('@/assets/images/athena/splash/splash207.png'),
    SPLASH106: require('@/assets/images/athena/splash/splash210.png'),
    SPLASH107: require('@/assets/images/athena/splash/splash206.png'),
    SPLASH108: require('@/assets/images/athena/splash/splash216.png'),
    SPLASH109: require('@/assets/images/athena/splash/splash208.png'),
    SPLASH110: require('@/assets/images/athena/splash/splash219.png'),
    SPLASH111: require('@/assets/images/athena/splash/splash225.png'),
    FLAG001: require('@/assets/images/athena/flags/flag103.png'),
    FLAG002: require('@/assets/images/athena/flags/flag101.jpeg'),
    FLAG003: require('@/assets/images/athena/flags/flag102.png'),
    FLAG004: require('@/assets/images/athena/flags/flag105.png'),
    FLAG005: require('@/assets/images/athena/flags/flag109.png'),
    FLAG006: require('@/assets/images/athena/flags/flag104.png'),
    FLAG007: require('@/assets/images/athena/flags/flag106.png'),
    FLAG008: require('@/assets/images/athena/flags/flag107.png'),
    FLAG009: require('@/assets/images/athena/flags/flag108.png'),
    DEFAULT: 'https://previews.123rf.com/images/apoev/apoev1804/apoev180400017/98627827-default-placeholder-businesswoman-half-length-portrait-photo-avatar-woman-gray-color.jpg',
  },
  WORLD: {
    LOGO: require('@/assets/images/world/logo.png'),
    W001: require('@/assets/images/world/world001.jpg'),
    W101: require('@/assets/images/world/world101.jpg'),
    W102: require('@/assets/images/world/world102.webp'),
    W103: require('@/assets/images/world/world103.jpg'),
  },
  CHATGPT: {
    V1: {
      LOGO: require('@/assets/images/chatgpt/v1/logo.png'),
      AVATAR: require('@/assets/images/chatgpt/v1/avatar.jpg'),
    },
  },
};